paths:
    db: "%(electrozart)s/scores_db"
    midi_out_base: "%(electrozart)s/../../output-mids"
    batch_models_out_base: "%(electrozart)s/../../output-models"
    graphs: "%(electrozart)s/../../output-graphs"

mongo:
    db: "tesis"
    scores_collection: "scores"
