parsers:
    midi:
        type: object
        path: electrozart.parsing.midi:MidiScoreParser
        args:
            print_warnings: False


writers:
    midi:
        type: object
        path: electrozart.writing.midi:MidiScoreWriter
        

            
            
