harmonic_context:
    tonic:
        type: object
        path: electrozart.algorithms.harmonic_context:TonicHarmonicContext
        args:
            nd: object:notes_distr
            seed: param:seed

    chord: 
        type: object
        path: electrozart.algorithms.harmonic_context:ChordHarmonicContext
        args:
            context_score: param:score
            notes_distr: object:notes_distr
            seed: param:seed
            
    phrase_repetitions:
        type: object
        path: electrozart.algorithms.crp.phrase_repetition:PhraseRepetitions
        args:
            harmonic_context_alg: object:chord
            seed: param:seed

    notes_distr:
        type: object
        path: electrozart.algorithms.harmonic_context.notes_distr:NotesDistr
        args:
            seed: param:seed


rhythm:
    hmm:
        type: object
        path: electrozart.algorithms.hmm.rhythm:RhythmHMM
        args:
            score: param:score
            n_measures: param:n_measures
            seed: param:seed
        
    phrase:
        type: object
        path: electrozart.algorithms.hmm.rhythm:ListRhythm
        args:
            rhythm_alg: object:hmm
            seed: param:seed
        
    phrase_cache:
        type: object
        path: electrozart.algorithms.hmm.rhythm:RhythmCacheAlgorithm
        args:
            algorithm: object:phrase
            input_key: 'phrase_id'
            seed: param:seed

contour:
    simple:
        type: object
        path: electrozart.algorithms.hmm.melody.complete_narmour_model_wo_must:SimpleContourAlgorithm
        args:
            seed: param:seed
            use_narmour: param:use_narmour

    phrase:
        type: object
        path: electrozart.algorithms.hmm.melody.complete_narmour_model:ContourAlgorithm
        args:
            algorithm: object:rhythm.phrase
            input_key: 'phrase_id'
            seed: param:seed
        
    phrase_cache:
        type: object
        path: electrozart.algorithms:CacheAlgorithm
        args:
            algorithm: object:phrase
            input_key: 'phrase_id'
            seed: param:seed

    simple_cache:
        type: object
        path: electrozart.algorithms:CacheAlgorithm
        args:
            algorithm: object:simple
            input_key: 'phrase_id'
            seed: param:seed
        
