from midistuff.writers.MidiOutFile import MidiOutFile
mof=MidiOutFile('prueba.mid')
mof.header(1,1)
mof.start_of_track()
mof.patch_change(1, 30)
mof.patch_change(2, 40)
mof.note_on(1)
mof.update_time(100)
mof.note_off(1)
mof.note_on(2)
mof.note_off(2)
mof.end_of_track()
mof.eof()
