scrapdaemon:
    type: config
    jobs_queue: object:local_job_queue
    responses_queue: object:responses_queue

store_scrap_result_daemon:
    type: config
    responses_queue: object:local_responses_queue

local_responses_queue:
    type: object
    path: meli_catalog.backend.queue:Queue
    args: 
        - object:local_file_system
        - config:responses_queue_path 

remote_responses_queue:
    type: object
    path: meli_catalog.backend.queue:Queue
    args: 
        - object:remote_file_system
        - config:responses_queue_path

local_job_queue:
    type: object
    path: meli_catalog.backend.queue:Queue
    args: 
        - object:local_file_system
        - config:job_queue_path 

remote_job_queue:
    type: object
    path: meli_catalog.backend.queue:Queue
    args: 
        - object:remote_file_system
        - config:job_queue_path

local_file_system:
    type: object
    path: meli_catalog.backend.fs:LocalFilesystem


remote_file_system:
    type: object
    path: meli_catalog.backend.fs:SSHFileSystem
    args:
        username: config:username
        host: config:host
        private_key_fname: config:private_key_fname 
        
banned_domains:
    - "www.youtube.com"
    - "flups.net"
    
    
