#!/usr/bin/python
import subprocess

def pdflatex():
    cmd= 'pdflatex -file-line-error -halt-on-error tesis.tex'
    process= subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    stdout= process.stdout.read()
    if 'no output PDF file produced' in stdout:
        print stdout
        return -1
    else:
        return 0

def bibtex():
    cmd= 'bibtex tesis'
    process= subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    return 0

def clean():
    cmd= "./clean"
    process= subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    return 0

def chained(*funcs):
    for f in funcs:
        print 'Executing %s' % f.__name__
        if f() != 0: break

chained(pdflatex, bibtex, pdflatex, pdflatex)
