notes_distr:
    type: object
    path: electrozart.algorithms.harmonic_context.notes_distr:NotesDistr
    args:
        score: param:score
        seed: param:seed

tonic_harmonic_context:
    type: object
    path: electrozart.algorithms.harmonic_context:TonicHarmonicContext
    args:
        nd: object:notes_distr
        seed: param:seed

chord_harmonic_context: 
    type: object
    path: electrozart.algorithms.harmonic_context:ChordHarmonicContext
    args:
        context_score: param:score
        notes_distr: object:notes_distr
        seed: param:seed
        
phrase_repetitions_harmonic_context:
    type: object
    path: electrozart.algorithms.crp.phrase_repetition:PhraseRepetitions
    args:
        harmonic_context_alg: object:chord_harmonic_context
        seed: param:seed

rhythm_hmm:
    type: object
    path: electrozart.algorithms.hmm.rythm:RythmHMM
    args:
        score: param:score
        n_measures: param:n_measures
        seed: param:seed
    
phrase_rhythm_alg:
    type: object
    path: electrozart.algorithms.hmm.rythm:ListRythm
    args:
        rythm_alg: object:rhythm_hmm
        seed: param:seed
    
phrase_rhythm_alg_cache:
    type: object
    path: electrozart.algorithms.hmm.rythm:RythmCacheAlgorithm
    args:
        algorithm: object:phrase_rhythm_alg
        input_key: 'phrase_id'
        seed: param:seed

phrase_contour_algorithm:
    type: object
    path: electrozart.algorithms.hmm.melody.complete_narmour_model:ContourAlgorithm
    args:
        algorithm: object:phrase_rhythm_alg
        input_key: 'phrase_id'
        seed: param:seed
    
